name: keyboard_visibility
description: Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
version: 0.5.6
author: faiyyaz <kfaiyyaz93@gmail.com>
homepage: https://github.com/Faiyyaz/flutter_keyboard_visibility

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_visibility: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
